In [7]:
from transformers import AutoModel, AutoTokenizer

token = "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"

model = "hf_stas/tiny-random-llama-2"
# model = "hf_lmsys/vicuna-7b-v1.3"
model = model.split("_")[-1]

full_model = AutoModel.from_pretrained(model
                                       , output_hidden_states=True,
                                       use_auth_token='',
                                      )
tokenizer = AutoTokenizer.from_pretrained(model,
                                          token=''
                                          # , use_auth_token=token
                                         )

Some weights of LlamaModel were not initialized from the model checkpoint at stas/tiny-random-llama-2 and are newly initialized: ['model.layers.0.self_attn.rotary_emb.inv_freq', 'model.layers.1.self_attn.rotary_emb.inv_freq']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [8]:
seq_ids = tokenizer("hi", return_tensors='pt')["input_ids"]


In [10]:
tokenizer("hi", return_tensors='pt')


{'input_ids': tensor([[  1, 229, 153, 132, 107, 108]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1]])}

In [10]:
embedding = full_model(seq_ids)["last_hidden_state"]

In [113]:
len(full_model(seq_ids)[0])

1

In [114]:
len(full_model(seq_ids).last_hidden_state[0])

6

In [11]:
full_model(seq_ids).last_hidden_state[0].detach().numpy().shape

(6, 16)

In [116]:
list(full_model(seq_ids).keys())

['last_hidden_state', 'past_key_values', 'hidden_states']

In [12]:
embedding = full_model(seq_ids)["last_hidden_state"].mean(axis=[0,1]).detach().numpy()

In [19]:
full_model(seq_ids)["last_hidden_state"].mean(axis=[0, 1])


tensor([-0.3220,  0.2277,  1.0253,  0.4318, -0.1543,  0.3265, -0.0627,  0.1382,
         0.2769, -0.2701, -0.7543,  0.2692,  0.2671,  0.3833,  0.1777, -0.0613],
       grad_fn=<MeanBackward1>)

In [26]:
full_model(seq_ids)["last_hidden_state"].max(axis=1).values[0]

torch.return_types.max(
values=tensor([[0.8830, 1.2890, 1.4374, 1.9147, 0.1934, 1.0196, 1.5842, 1.8089, 2.1782,
         0.5392, 0.3511, 2.8626, 0.8909, 1.6265, 1.5099, 0.7303]],
       grad_fn=<MaxBackward0>),
indices=tensor([[5, 1, 2, 0, 5, 4, 1, 4, 5, 3, 1, 2, 0, 5, 0, 2]]))

In [8]:
full_model(seq_ids)["last_hidden_state"]

tensor([[[-1.1176, -0.5227,  0.7872,  1.9147,  0.1836,  0.2644,  0.2650,
          -0.3453, -0.2523, -1.4493, -2.0100,  0.0400,  0.8909,  0.5693,
           1.5099,  0.0061],
         [-0.1771,  1.2890,  1.1390,  1.5421, -0.4276,  0.8708,  1.5842,
          -0.9612,  0.2046,  0.4822,  0.3511, -1.1898,  0.8283, -0.5328,
           1.2452, -1.2789],
         [ 0.6879, -0.1596,  1.4374,  0.7793,  0.1343, -0.5861, -1.0100,
          -0.6172,  0.0451,  0.3053, -0.2175,  2.8626,  0.6230,  0.1501,
          -1.2365,  0.7303],
         [-1.6715,  0.3689,  0.9377,  0.1156, -0.4611,  0.8296, -0.5593,
           1.1896,  1.2797,  0.5392, -2.3945, -0.3266,  0.6564, -0.9172,
          -0.2626, -0.1163],
         [-0.5368,  0.7225,  0.4267, -0.1495, -0.5483,  1.0196, -1.0024,
           1.8089, -1.7940, -1.3499, -0.1630, -0.9501, -0.6590,  1.4036,
          -0.0968,  0.5737],
         [ 0.8830, -0.3320,  1.4241, -1.6115,  0.1934, -0.4392,  0.3459,
          -0.2458,  2.1782, -0.1479, -0.0917,  1.179

In [12]:
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

gen_pipe = pipeline(
            "feature-extraction",
            model=model,
            tokenizer=tokenizer,
            device='cuda:0'
        )

Some weights of LlamaModel were not initialized from the model checkpoint at stas/tiny-random-llama-2 and are newly initialized: ['model.layers.1.self_attn.rotary_emb.inv_freq', 'model.layers.0.self_attn.rotary_emb.inv_freq']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [13]:
gen_pipe("hi")

[[[-1.1175556182861328,
   -0.5226937532424927,
   0.7871804237365723,
   1.9146766662597656,
   0.18356014788150787,
   0.26437053084373474,
   0.2650412619113922,
   -0.34527406096458435,
   -0.2523225247859955,
   -1.449312686920166,
   -2.009962320327759,
   0.0399501770734787,
   0.8908973932266235,
   0.5693443417549133,
   1.50994873046875,
   0.006138209253549576],
  [-0.17712020874023438,
   1.289019227027893,
   1.1389769315719604,
   1.5420831441879272,
   -0.42755013704299927,
   0.8707579970359802,
   1.5841963291168213,
   -0.9612216949462891,
   0.20458737015724182,
   0.4821988344192505,
   0.3510575592517853,
   -1.1897553205490112,
   0.8282694816589355,
   -0.5327813029289246,
   1.245207667350769,
   -1.2788676023483276],
  [0.687866747379303,
   -0.15962690114974976,
   1.437384843826294,
   0.7793460488319397,
   0.1342785507440567,
   -0.5860916376113892,
   -1.0099701881408691,
   -0.6171806454658508,
   0.04508574306964874,
   0.30527830123901367,
   -0.2175338

In [18]:
len(gen_pipe("hi")[0])

6

In [75]:
from sklearn.metrics.pairwise import cosine_similarity

In [1]:
model = "hf_stas/tiny-random-llama-2"
model = model.split("_")[-1]

full_model = AutoModel.from_pretrained(model
                                       , output_hidden_states=True,
                                       # , use_auth_token=token
                                       device='cuda:0'
                                      )
tokenizer = AutoTokenizer.from_pretrained(model
                                          # , use_auth_token=token
                                         )

NameError: name 'AutoModel' is not defined

In [77]:
seq_ids = tokenizer("Hey Tutor! What is Data Science?", return_tensors='pt')["input_ids"]
embedding = full_modelDEFAULT_MODEL_NAME = "sentence-transformers/all-mpnet-base-v2"
.detach().numpy()


In [78]:
len(full_model(seq_ids))

3

In [79]:
full_model(seq_ids)['last_hidden_state'].detach().numpy().shape

(1, 46, 16)

In [80]:
fm_vec = full_model(seq_ids).last_hidden_state[0].detach().numpy()


In [81]:
fm_vec.shape

(46, 16)

In [82]:
gen_pipe = pipeline(
            "feature-extraction",
            model=model,
            tokenizer=tokenizer,
            device='cuda:0'
        )

Some weights of LlamaModel were not initialized from the model checkpoint at stas/tiny-random-llama-2 and are newly initialized: ['model.layers.1.self_attn.rotary_emb.inv_freq', 'model.layers.0.self_attn.rotary_emb.inv_freq']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [89]:
import numpy as np
gp_vec = np.array(gen_pipe("Hey Tutor! What is Data Science?")[0])

In [88]:
gp_vec.shape

(1, 46, 16)

In [86]:
cosine_similarity(fm_vec.reshape(1, -1), gp_vec.reshape(1, -1))

array([[1.]])

In [85]:
fm_vec.shape

(46, 16)

In [72]:
gp_vec.shape

(46, 16)

In [91]:
model

'stas/tiny-random-llama-2'

In [90]:
from langchain.embeddings import HuggingFaceEmbeddings

In [94]:
embedding_model = HuggingFaceEmbeddings(
                model_name=model,
                model_kwargs={"device": "cuda:0"                 
                },
                encode_kwargs={'normalize_embeddings': False})

No sentence-transformers model found with name /home/reventh/.cache/torch/sentence_transformers/stas_tiny-random-llama-2. Creating a new one with MEAN pooling.
Some weights of LlamaModel were not initialized from the model checkpoint at /home/reventh/.cache/torch/sentence_transformers/stas_tiny-random-llama-2 and are newly initialized: ['model.layers.1.self_attn.rotary_emb.inv_freq', 'model.layers.0.self_attn.rotary_emb.inv_freq']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [95]:
embedding_model.embed_query("Hey Tutor! What is Data Science?")

Using pad_token, but it is not set yet.


ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.

In [101]:
def func(**kwargs):
    if 'a' in kwargs:
        print(kwargs['a'])
    print(sum(kwargs.values()))

In [102]:
func(a=1, b=1)

1
2


In [104]:
tokenizer("Hey Tutor! What is Data Science?", return_tensors='pt')['input_ids']

tensor([[  1, 229, 153, 132,  75, 104, 124, 229, 153, 132,  87, 120, 119, 114,
         117,  36, 229, 153, 132,  90, 107, 100, 119, 229, 153, 132, 108, 118,
         229, 153, 132,  71, 100, 119, 100, 229, 153, 132,  86, 102, 108, 104,
         113, 102, 104,  66]])

In [105]:
DEFAULT_MODEL_NAME = "sentence-transformers/all-mpnet-base-v2"


In [121]:
import sentence_transformers

In [122]:
model = sentence_transformers.SentenceTransformer(DEFAULT_MODEL_NAME)

In [123]:
model.encode("Hey Tutor! What is Data Science?").shape

(768,)

In [1]:
from model.llm_encoder import LLMBasedEmbeddings

In [2]:
llmmodel = LLMBasedEmbeddings("stas/tiny-random-llama-2", aggr='mean')

/home/reventh/anaconda3/envs/lmtutor/lib/python3.9/site-packages/transformers/modeling_utils.py:2193: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Some weights of LlamaModel were not initialized from the model checkpoint at stas/tiny-random-llama-2 and are newly initialized: ['model.layers.1.self_attn.rotary_emb.inv_freq', 'model.layers.0.self_attn.rotary_emb.inv_freq']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [3]:
llmmodel.embed_documents(["Hey Tutor! What is Data Science?", "Hey Tutor! What is Data Science?"])

[array([-0.10889034,  0.05917635,  0.35102242,  0.46370503, -0.0371076 ,
         0.06390191, -0.14735016, -0.09830719,  0.19880925,  0.15226689,
        -0.3408267 ,  0.21463007,  0.36214927, -0.20361033,  0.13497443,
         0.03197159], dtype=float32),
 array([-0.10889034,  0.05917635,  0.35102242,  0.46370503, -0.0371076 ,
         0.06390191, -0.14735016, -0.09830719,  0.19880925,  0.15226689,
        -0.3408267 ,  0.21463007,  0.36214927, -0.20361033,  0.13497443,
         0.03197159], dtype=float32)]

In [12]:
import argparse
import os

from dataset import prepare_data, get_parsed_data
from model.llm_langchain_tutor import LLMLangChainTutor
from utils import get_cache_dir, get_document_folder, get_vector_file
from metrics import EmbeddingModelMetrics
from loguru import logger
from tqdm import tqdm
import torch
import shutil

In [13]:
embedding_model = 'instruct_embeddings'
llm_model = 'hf_stas/tiny-random-llama-2'   
embed_device = 'cuda:0'
llm_device = 'cuda:0'
base_data_dir = '.cache'
cache_dir = base_data_dir
dataset_name = 'squad'
debug = True

In [19]:
lmtutor = LLMLangChainTutor(
        embedding=embedding_model,
        llm=llm_model,
        embed_device=embed_device,
        llm_device=llm_device,
        cache_dir=cache_dir,
        debug=debug,
        token = "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",
    )

In [20]:
doc_folder = get_document_folder(base_data_dir, dataset_name, debug)
vec_file = get_vector_file(base_data_dir, dataset_name, debug)
if os.path.exists(vec_file):
    shutil.rmtree(vec_file)

In [21]:
os.path.exists(vec_file)

False

In [16]:
splitted_documents = lmtutor._load_document(doc_folder, glob="*.txt", chunk_size=400, chunk_overlap=10)

100%|██████████| 21/21 [00:00<00:00, 223.52it/s]


In [17]:
splitted_documents

[Document(page_content="About 80% of undergraduates and 20% of graduate students live on campus. The majority of the graduate students on campus live in one of four graduate housing complexes on campus, while all on-campus undergraduates live in one of the 29 residence halls. Because of the religious affiliation of the university, all residence halls are single-sex, with 15 male dorms and 14 female dorms. The university maintains a visiting policy (known as parietal hours) for those students who live in dormitories, specifying times when members of the opposite sex are allowed to visit other students' dorm rooms; however, all residence halls have 24-hour social spaces for students regardless of gender. Many residence halls have at least one nun and/or priest as a resident. There are no traditional social fraternities or sororities at the university, but a majority of students live in the same residence hall for all four years. Some intramural sports are based on residence hall teams, w

In [18]:
if not os.path.exists(vec_file):
        logger.info("Creating vector store...")
        lmtutor.generate_vector_store(
            doc_folder, vec_file, glob="*.txt", chunk_size=400, chunk_overlap=10
        ) #TODO: glob not always text, can be .pdf
else:
        logger.info("Loading vector store...")
        lmtutor.load_vector_store(vec_file)

2023-11-20 17:21:10.968 | INFO     | __main__:<module>:2 - Creating vector store...
100%|██████████| 21/21 [00:00<00:00, 222.64it/s]


In [8]:
dataset = get_parsed_data(dataset_name, base_data_dir=base_data_dir, debug=True)

In [9]:
dataset

question  \
0   To whom did the Virgin Mary allegedly appear i...   
1   What is in front of the Notre Dame Main Building?   
2   The Basilica of the Sacred heart at Notre Dame...   
3                   What is the Grotto at Notre Dame?   
4   What sits on top of the Main Building at Notre...   
..                                                ...   
95  In 1919 a new president of Notre Dame was name...   
96  Over how many years did the change to national...   
97  Those who attended a Jesuit college may have b...   
98  The Notre Dame football team got a new head co...   
99  What was the amount of wins Knute Rockne attai...   

                                     answer  doc_id  
0                Saint Bernadette Soubirous      17  
1                 a copper statue of Christ      17  
2                         the Main Building      17  
3   a Marian place of prayer and reflection      17  
4        a golden statue of the Virgin Mary      17  
..                                      ...     ...  
95                       Father James Burns      12  
96                              three years      12  
97                       Harvard Law School      12  
98                             Knute Rockne       6  
99                                      105       6  

[100 rows x 3 columns]

In [10]:
true_label, predicted_label = [], []
for _, row in tqdm(dataset.iterrows(), total=len(dataset)):
        question = row["question"]
        doc_id = row["doc_id"]

        # get context from context_id
        relevant_documents = lmtutor.similarity_search_topk(question)
        relevant_documents_ids = [
            int(doc.metadata["source"].split("/")[-1].split(".")[0])
            for doc in relevant_documents
        ]

        # Update counters based on the top-k logic
        is_correct = doc_id in relevant_documents_ids
        predicted_label.extend([1 if is_correct else 0])
        true_label.extend([1])
        ## (true, predicted)
        # metrics_calculator.update([1 if is_correct else 0], [1])


# Calculate metrics
metrics_calculator = EmbeddingModelMetrics(true_label, predicted_label)
precision = metrics_calculator.calculate_precision()
recall = metrics_calculator.calculate_recall()
f1_score = metrics_calculator.calculate_f1_score()
accuracy = metrics_calculator.calculate_accuracy()

100%|██████████| 100/100 [00:00<00:00, 103.18it/s]
/home/reventh/anaconda3/envs/lmtutor/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [11]:
print(precision, recall, f1_score, accuracy)

1.0 0.95 0.9743589743589743 0.95


In [10]:
lmtutor.gen_vectorstore.similarity_search('query', k=10)

[Document(page_content="As at most other universities, Notre Dame's students run a number of news media outlets. The nine student-run outlets include three newspapers, both a radio and television station, and several magazines and journals. Begun as a one-page journal in September 1876, the Scholastic magazine is issued twice monthly and claims to be the oldest continuous collegiate publication in the United States. The other magazine, The Juggler, is released twice a year and focuses on student literature and artwork. The Dome yearbook is published annually. The newspapers have varying publication interests, with The Observer published daily and mainly reporting university and other news, and staffed by students from both Notre Dame and Saint Mary's College. Unlike Scholastic and The Dome, The Observer is an independent publication and does not have a faculty advisor or any editorial oversight from the University. In 1987, when some students believed that The Observer began to show a 